services:
  nginx:
    container_name: url-shortener-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  backend:
    container_name: url-shortener-backend
    image: cismoski/url-shortener-backend:latest
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  db:
    container_name: url-shortener-db
    image: postgres:17.5-alpine3.22
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - url_shortener_data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "5"

  frontend:
    container_name: url-shortener-frontend
    image: cismoski/url-shortener-frontend:latest
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

volumes:
  url_shortener_data:
    driver: local
